---
title: "Items to revisit related to Analytics Edge Course"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Related to Week 6 (clustering)
1. Using data in wk6/movieLens.txt and R commands in Unit6_Netflix.R, get excel output
as shown in Video 7 ("Hierarchical Clustering in R") of lecture sequence "Recommendations Worth a Million:An Introduction to Clustering"

## Related to Week 5 (text analytics) 
1. Read vignettes for to R packages related to ngrams. The packages are: 'RTextTools', 'tau',
'RWeka', and 'textcat'

## Related to Wk7
* Familiarize yourself with using maps and ggmap packages. See video 5 from lecture segment 2 of Unit 7 and wk7/Unit7_Crime.R

* Follow steps below to pull up map of chicago: in wk7/Unit7_Crime.R

**To run ggmap and get_map in ggmap pkg (From Wk7:Sequence2:Video5)** 
1. Get Google API from Google APIs. 
2. Enable Maps Static API and geocoding API. 
3. Go to the geocoding API that you have enabled. Click on credentials and ask for a key. Copy this key. 
4. Run below code:

```
if(!requireNamespace("devtools")) install.packages("devtools") devtools::install_github("dkahle/ggmap", ref = "tidyup", force = TRUE)

library(ggmap) register_google(key = "yourAPI")
``` 
where yourAPI is the key you copied in step 3.  If you're unable to run ggmap, you'll still be able to run the quick question after the video.

* Using tweets dataset, make word cloud related to only tweets with negative sentiment. (avg value -1 or less) 

* Make some heatmaps (see wk7/Unit7_Crime.R and associated videos)

* Figure out how to put tick marks on x-axis of histogram. See 2nd histogram of problem 4 of parole dataset ('Visualizing attributes of parole violators') from HW7. Need ticks for every 0.1 step in x-axis. 




## Miscellaneous 
1. Practice melting and reshaping data (see households.csv in wk7)

## Related to Wk3
1. Review Imputation (wk3 recitation)